# Site settings
title: Carl Wood
email: carl@whiteoctober.co.uk
description: > # this means to ignore newlines until "baseurl:"
  London-based front-end developer with a passion for beautiful markup. I support BWFC, and play bass.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carlwood.net" # the base hostname & protocol for your site
twitter_username: carljwood
github_username:  carlwood

# Build settings
markdown: kramdown
permalink: blog/:year/:title
higlighter: true

# Google Analytics
ga_domain: carlwood.net
ga_tracking_id: UA-41063708-1
