# Site settings
title: Carl Wood - Senior frontend developer portfolio
email: cjwood17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brighton-based Senior Frontend Developer with 10 years' experience of building user interfaces
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://carlwood.github.io" # the base hostname & protocol for your site
github_username:  carlwood

# Build settings
markdown: kramdown
permalink: blog/:title
higlighter: true
sass:
  style: compressed

# Google Analytics
ga_domain: carlwood.github.io
ga_tracking_id: UA-41063708-1
