# Site settings
title: Carl Wood - Front-end developer portfolio
email: cjwood17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brighton-based experienced front-end developer with a passion for beautiful markup.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carlwood.net" # the base hostname & protocol for your site
twitter_username: carljwood
github_username:  carlwood

# Build settings
markdown: kramdown
permalink: blog/:title
higlighter: true
sass:
  style: compressed

# Google Analytics
ga_domain: carlwood.net
ga_tracking_id: UA-41063708-1
